api.host=https://api.growingio.com
send.msg.interval=100
send.msg.thread=3
msg.store.queue.size=500
logger.level=debug
logger.implementation=io.growing.sdk.java.logger.GioLoggerImpl
run.mode=production
logger.file.enabled=false
logger.file.path=/logs
logger.file.max_size=10
logger.file.max_days=-1