#???????
api.host=https://api.growingio.com
#????????,??ms??? 100?
send.msg.interval=100
#???????? ??? 3?
send.msg.thread=3
#?????? ??? 500?
msg.store.queue.size=500
#?????? (debug | error)
logger.level=debug
#??????????
logger.implementation=io.growing.sdk.java.logger.GioLoggerImpl
#?????test:?????????????production: ????
run.mode=production
# ????, ??????????????
#proxy.host=127.0.0.1
#proxy.port=3128
# ??????????, ????????????????
#proxy.user=demo
#proxy.password=demo
#http ??????
#connection.timeout=2000
#http ??????
#read.timeout=2000
# ?????????????????????????????debug????????????????send.msg.thread?????????
# ????????????????GIOSendBeRejectedException?????????????????????
# ????????shutdownAwait??????????JVM???????????????????????????????
# msg.store.strategy=abortPolicy
# ????????0.5???????????????????debug????????????????????????0.5??????
# ???????????????????????????"??"???????????????????
# msg.store.queue.load_factor=0.5
# ??????????????
# logger.file.enabled=false
# ??????
# logger.file.path=/logs
# ???????????????MB
# logger.file.max_size=10
# ???????-1??????
# logger.file.max_days=-1
# ?????? ??????
# sync.read.timeout=2000
# ?????? ??????
# sync.connection.timeout=2000